language: ruby

rvm: 2.6.5

cache: bundler

branches:
    only:
        build

before_install:
    - gem update --system
    - gem install bundler

install: bundle install

script:
    - jekyll build

env:
    global:
        secure: "NxUPoRe7/pqW7xwo9S6YdIJZNmBI421CI+bWLkrPL0ARHUFhVz0gr5FGfflphTK2G56kqLvZqDXOIIj/Td55zI+Ta+GjKRHfgqs5htSVX7xGXRwL8Gij4pkOZbyjfrvEl36yxiWlnOenn4unSIwQLKMEk1Sn0mKnChkdZ5B29XNYBkjY1QvmFCuqlLsQveAeEvD+drReBN5RT7BTyTH9SEDI5pwNITbc4R4aGfruU/Zo22ybPU7BUJ15I0ZdXKxIAMyJUgd0jje2k6pfEOW8hxUQJ0kN0JT0VHJUuU2Bqfya76lYlDuA9amZy1xJiQW7s883ynSWZPg3ql5KkshI2xyVi2jhUJ3v8k5Qo0lpNxBAVe3X6l1LahmZQXfe5sJ/IXiL9vKCqeaztU0rdgQR/lzhi3LllT6J+wXqWpc+QtgkS4TgjCoWyjD5tbDgG5CYvVT9LtNdJiv7M9As3zTugzNWvCifcNcDWpp1ab2u+ugWAZpGFS9mTnL9B1+I9+wPfQPWGP9rY6pDeDcbLQjflHFlF5sWZaulUA9ZQ39Prf8ATSvr0qJDFdYLVHBGA2joGdkPR+xOgNQC7D6pUiGjQq5t2Qsru6VcS/+5MEAaIyDx2fCX6mjK1KdGkLuYV3tiSsWxg9UT4coM8oQYnzGQ6JwAhCg2lvdzEwvnju8l9lk="

deploy:
    provider: pages
    skip_cleanup: true
    keep_history: true
    github_token: $GH_TOKEN
    on:
        branch: build
    target_branch: master
    local_dir: _site
