language: ruby

rvm: 2.6.6

cache: bundler

branches:
    only:
        build

before_install:
    - gem install bundler

install: bundle install

script:
    - jekyll build

env:
    global:
        secure: "Av+KTwRo9T7JkCP2buOYF+33TXzx1Ykj4K+YA/H6Ed78xYKc+VQJjJH1LBB4jcWHyjQ/mRtIuprYU4GriydgiEMrD+9s+WfLtswVkqD5Ql79fqw68XHtAXgAIyf7qFbM3jeMOmATycm2zhnwXbQ5DtJQ6pQWtqufDIQncBtTYY1lgYtVH0+PT98u0asgzyenn0r9XpV5CYCxozybvm8ZmeA3Lhg1/44ZG+1SQlu6u3e2XH3zFcsLGP5UvnczimjP2OZ2x2rlLNZkLM1HD/oUPZF2Wmo2mo/gBDXEudjOSACdBEp3nVQEU6LQW1+rIrttqhi7+mMPbirndy1+Z33SiqPk2krZQ24eRMgKORkNOLqPwvOuwZM5WUqiv3WV7PvL31hbLA0E7sWuAOezhF2GiZIiAg+VEk258Yc3oLYt2uLk+XNYLWpkgwLkFFoJ4YC6UtrreD2lYKkUBxutw3utsI8XvL40Zb+lm1K9jkYsJ49NADgRddfV73D5o0amPrh7D660WJ9NAbkAgNpwNsH2AlpRYXMSsRN9y4ztI7ltOBX/1n/BAt2j3ZkLZeQHeIvRDrZtgqf008lFAn2/YXUiL80fGv0vnLBH84vzg/Q0TmZ20slf/4ToKWNfD/C51MhvXQa/KAuyKe0crI17PxHRMIZCtyyeN++xP67EbmUaSZo="

deploy:
    provider: pages
    edge: true
    github_token: $GH_TOKEN
    on:
        branch: build
    target_branch: master
    local_dir: _site
