title: UMD flavor physics and CP violation group

markdown: kramdown
repository: umd-lhcb/umd-lhcb.github.io

minify_html: true

# Minify generated CSS
sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-autoprefixer
    - jekyll-scholar

jekyll_tidy:
    compress_html: false

scholar:
    sort_by: year
    order: descending
    bibtex_filters: []
    style: _bibliography/apa-custom.csl
    #bibliography_list_tag: ul  # Entries not numbered if tagged this way

# Generating navbar programmatically
navigation:
    - title: Home
      url: /index.html
    - title: People
      url: /pages/people.html
    - title: Papers
      url: /pages/papers.html
    - title: Talks
      url: /pages/talks.html
    - title: Links
      url: /pages/links.html

# Exclude from processing.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - push.sh
    - README.md
    - README.local.md
    - LICENSE.txt
    - assets/images/event_display_2d.jpg
    - assets/images/babar_logo.png
    - assets/images/physics_logo_final_white.png
    - assets/images/photos/group_members-181121.jpg
