title: UMD flavor physics and CP violation group
description: Reference webpage for software written by UMD LHCb people.

markdown: kramdown
repository: umd-lhcb/umd-lhcb.github.io

# Minify generated CSS
sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-autoprefixer
    - jekyll-tidy

jekyll_tidy:
    compress_html: false

# Generating navbar programmatically
navigation:
    - title: Home
      url: /index.html
    - title: People
      url: /people.html
    - title: Software
      url: /software.html

# Current member of the group
current_members:
    - name: Hassan Jawahery
      title: Distinguished University Professor and the Gus T. Zorn Professor
      email: jawahery@physics.umd.edu
      address: 3208G Physical Sciences Complex
    - name: Manuel Franco Sevilla
      title: Assistant Professor
      email: manuelf@umd.edu
      address: 3114 Physical Sciences Complex
      website: http://flavor.physics.umd.edu/manuelf
    - name: Sally Megonigal
      title: Group Secretary
      email: smegonig@umd.edu
      address: 3208 Physical Sciences Complex
    - name: Thomas O'Bannon
      title: Electrical Engineer
      email: tobannon@umd.edu
      address: 3208E Physical Sciences Complex
    - name: Brian Hamilton
      title: Postdoc
      email: bkham@umd.edu
      address: 3105 Physical Sciences Complex
    - name: William Parker
      title: Postdoc
      email: wcparker@umd.edu
      address: 3105 Physical Sciences Complex
    - name: Zishuo Yang
      title: Graduate Student
      email: yangzs@umd.edu
      address: 3101 Physical Sciences Complex
    - name: Yipeng Sun
      title: Graduate Student
      email: syp@umd.edu
      address: 3101 Physical Sciences Complex

# Past member of the group
past_members:
    - name: Jack Wimberley
      title: PhD, graduated
    - name: Jason Andrews
      title: PhD, graduated

# Software on github
repos:
    - url: https://github.com/ZishuoYang/UT-Backplane-mapping
      descr: Altium auxiliary netlists for PigTail and DCB
      has_release: true
    - url: https://github.com/ypsun-umd/gbtx_communication_doc
      descr: GBTx daughter board and DCB user-friendly manual
      has_release: true
    - url: https://github.com/umd-lhcb/docker-images
      descr: Dockers for LHCb data analysis
    - url: https://github.com/umd-lhcb/umd-lhcb.github.io
      descr: Group website
    - url: https://github.com/ypsun-umd/dcb_design_verification_measurements
      descr: DCB design verification measurements
      has_release: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
